# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

service_type: "common"

# general settings
log-level: info
retain-mode: false
k8s-connection-timeout-second: 120
write-merger-connection-timeout-second: 120

# write merger
write-merger-port: 9748
write-merger-max-db-connection: 50

# db poller
db-poller-interval-second: 120
db-poller-max-db-connection: 10
